### PR TITLE
Update datamyx semvar

### PR DESCRIPTION
**Pull request by ros3bud**
Locks the version at the one before the URL updates were made.

### CODE REVIEW

**Comment by ros3bud** [comment]
@alexkwolfe, LGTY?

**Comment by alexkwolfe** [comment]
I think Chris is making a change to the Clearbit integration that will obviate the need for this change.

**Comment by alexkwolfe** [comment]
cc @cgrayson

**Comment by cgrayson** [comment]
@jgrayson676 actually made the change, but yes, it's been npm published and shouldn't cause these kinds of problems again. It was discussed some in #leadconduit but I should have been more clear that we'd changed direction on how to address this.

**Comment by ros3bud** [comment]
Ok. I've removed the script test. @alexkwolfe or @cgrayson, LGTY?

**Comment by cgrayson** [comment]
Looks like there's no line changes left here, now. :smiley:  https://github.com/activeprospect/leadconduit-integrations/pull/43/files

**Comment by ros3bud** [comment]
I see. Ok, well, we want datamyx to be at ^1.0.0 and it is in master, so this PR is no longer needed.

**Pull request closed without merging**
