### PR TITLE
Removed First Orion module from package.json

### PR DESCRIPTION
**Pull request by jarrmill**
Ticket can be found [here](https://app.clubhouse.io/active-prospect/story/3987/decommission-the-first-orion-integrations).

Will check on 01/02 on why this PR is failing.

### CODE REVIEW

**Comment by jarrmill** [comment]
Regarding the failing TravisCI tests, I'm hitting a roadblock on getting them to pass. They pass with Node 8, but are failing on Node 13.

I've written more about the failing tests on [this issue](https://github.com/activeprospect/leadconduit-integrations/issues/133)

**Comment by chasingSublimity** [comment]
v12 failures are known, but no plans to fix just yet. We've got a bit of time.

https://app.clubhouse.io/active-prospect/story/2480/timeout-tests-in-the-leadconduit-integrations-package-fail-on-node-12

**Comment by chasingSublimity** [comment]
Could you do me a favor and add v10 to travis?

**Comment by chasingSublimity** [comment]
@jarrmill Sorry, i meant adding node 10 in addition to node 8 :D 

We aren't quite off 8 yet. 😬

**Comment by jarrmill** [comment]
@chasingSublimity I just added Node 8 back to the Travis yml file, so I think it should be g2g. If so, we are finally ready to merge this

**Pull request merged**
