### PR TITLE
update semver to range

### PR DESCRIPTION
**Pull request by ros3bud**
@alexkwolfe, do you mind if I add a range to the dependency for Pipeline? This will allow me to work quickly to QA my code.

### CODE REVIEW

**Comment by alexkwolfe** [comment]
Why do you want the upper bound to be 0.1.0 and not just 0.0.X?

**Comment by ros3bud** [comment]
I didn't realize that would work until you asked so I will update it to that.

**Comment by alexkwolfe** [comment]
I don't understand your reply.

**Comment by ros3bud** [comment]
Meant I didn't  know 0.0.X was legit to use until you asked and I tested it - then saw that it makes [ [ '>=0.0.0', '<0.1.0' ] ] available. So I've now changed it to 0.0.X.

**Comment by alexkwolfe** [comment]
I would recommend using the tilde instead, even though it does the same thing. We use tilde in other places, but not `.X`.

**Comment by ros3bud** [comment]
Shoot, now I don't follow your reply. Do you mean ~0.0.X?

**Comment by alexkwolfe** [comment]
If you look at the dependencies in this project you won't see any usages of `.X`. You'll see `~` and `^`. Let's keep the semver ranges consistent by using one of those instead of `.X`.

**Comment by ros3bud** [comment]
Got it & updated.

**Comment by alexkwolfe** [comment]
LGTM

**Pull request merged**
